# Generated by Django 5.2.17 on 2026-08-28 15:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier / LiveKit Room ID', primary_key=True, serialize=False)),
                ('caller_number', models.CharField(help_text='Caller phone number', max_length=32)),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='RINGING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the incoming call was detected')),
                ('answered_at', models.DateTimeField(blank=True, help_text='Timestamp when the call was auto-answered', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when the call ended', null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total active call duration in seconds')),
                ('dialogue_transcript', models.JSONField(blank=True, default=list, help_text="Turn-by-turn transcribed dialogue list [{'speaker': 'caller'|'agent', 'text': '...', 'timestamp': '...'}]")),
                ('is_processed', models.BooleanField(default=False, help_text='Flag indicating whether post-call LLM analysis has run')),
            ],
            options={
                'verbose_name': 'Call Session',
                'verbose_name_plural': 'Call Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number in standard international/local format (e.g. +919876543210)', max_length=32, unique=True)),
                ('contact_name', models.CharField(blank=True, help_text='Name of the person or organization (e.g. Mom, Boss Rohan, Amazon Delivery)', max_length=120)),
                ('relationship', models.CharField(choices=[('FAMILY', 'Family Member'), ('WORK', 'Work / Business Colleague'), ('FRIEND', 'Friend'), ('DELIVERY', 'Delivery / Service Agent'), ('UNKNOWN', 'Unknown Caller'), ('SPAM', 'Spam / Telemarketer')], default='UNKNOWN', help_text='Categorized relationship to Karamveer', max_length=20)),
                ('custom_system_prompt', models.TextField(help_text="Special instructions for how the AI agent must speak to this specific person (e.g. 'Speak with high respect and address as Sir', 'Tell Mom I am in a meeting and will reach home by 8 PM').")),
                ('preferred_language', models.CharField(default='Hindi', help_text='Preferred speaking language (e.g. Hindi, English, Hinglish)', max_length=30)),
                ('is_vip', models.BooleanField(default=False, help_text='If true, marks call insights as high priority')),
                ('is_blocked', models.BooleanField(default=False, help_text='If true, agent rejects or immediately dismisses the call')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Personality Rule',
                'verbose_name_plural': 'Contact Personality Rules',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CallInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_motive', models.CharField(help_text="Core purpose of the call (e.g. 'Asking for meeting reschedule', 'Delivery OTP verification')", max_length=255)),
                ('executive_summary', models.TextField(help_text='Clean concise summary of the entire call for quick reading')),
                ('caller_personality_notes', models.TextField(blank=True, help_text='Observed personality traits, emotional state, or urgency of the caller (e.g. Calm, Hurried, Anxious, Angry, Polite)')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low / Casual'), ('MEDIUM', 'Medium / Informational'), ('HIGH', 'High / Important'), ('CRITICAL', 'Critical / Emergency')], default='LOW', help_text='Assessed urgency level', max_length=20)),
                ('action_items', models.JSONField(blank=True, default=list, help_text='List of follow-up tasks for Karamveer extracted from the call')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='telephony.callsession')),
            ],
            options={
                'verbose_name': 'Call Insight & Analysis',
                'verbose_name_plural': 'Call Insights & Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddField(
            model_name='callsession',
            name='contact_personality',
            field=models.ForeignKey(blank=True, help_text='Matched personality profile if number was registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='telephony.contactpersonality'),
        ),
    ]
